---
title: "ADAPTS Vignette #3"
author: "Xinyi Yan"
date: "6/29/2020"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{ADAPTS3}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r libraries, echo=FALSE, warning=FALSE}
devtools::install_github("sdanzige/ADAPTSdata3")
library(ADAPTS)
library(ADAPTSdata3)
library(preprocessCore)
library(pheatmap)
library(mclust)
library(parallel)
library(ranger)
doParallel::registerDoParallel(cores = parallel::detectCores())

```

deconvolution function
```{r}
method <- 'DCQ'
normalData <- log(ADAPTSdata3::normalData.5061+1)

scMatrixTest <- function(normalData, randomize = TRUE, skipShrink=FALSE, handMetaCluster=FALSE) {
  
  if(randomize==TRUE) { set.seed(Sys.time()) } ##different seed every run
  resList <- list()

#step 1a: Build a cell speific gList using ranger forest
trainTestSet <- splitSCdata(normalData, numSets=2, randomize = TRUE)
trainSet <- trainTestSet[[1]]
testSet <- trainTestSet[[2]]
trainSet.30sam <- ADAPTS::scSample(RNAcounts = trainSet, groupSize = 30, randomize = TRUE)
trainSet.3sam <- ADAPTS::scSample(RNAcounts = trainSet, groupSize = 3, randomize = TRUE)



#step 1b: Build a deconvolution seed matrix using ranger forest and estiamte

genesInSeed <- 100
seedMat<-buildSeed(trainSet=trainSet, trainSet.3sam = trainSet.3sam, trainSet.30sam = trainSet.30sam, genesInSeed = genesInSeed, groupSize = 30, randomize = TRUE, num.trees = 1000, plotIt = FALSE)  

pseudobulk.test <- data.frame(test=rowSums(testSet))
pseudobulk.test.counts<-table(sub('\\..*','',colnames(testSet)))
actFrac.test <- 100 * pseudobulk.test.counts / sum(pseudobulk.test.counts)

estimates.test <- as.data.frame(ADAPTS::estCellPercent.DCQ(seedMat, pseudobulk.test))
colnames(estimates.test)<-'seed'

estimates.test$actFrac<-round(actFrac.test[rownames(estimates.test)],2)

resList[['testAcc.seed']]<-seedAcc<-calcAcc(estimates=estimates.test[,1], reference=estimates.test[,2])



#step 1c: all gene
allGeneSig <- apply(trainSet.3sam, 1, function(x){tapply(x, colnames(trainSet.3sam), mean, na.rm=TRUE)})
dim(allGeneSig)
dim(trainSet.3sam)
estimates.allGene <- as.data.frame(ADAPTS::estCellPercent.DCQ(t(allGeneSig), pseudobulk.test))
colnames(estimates.allGene)<-'all'
estimates.test<-cbind(estimates.allGene,estimates.test)
resList[['testAcc.all']]<-allAcc<-calcAcc(estimates=estimates.test[,1], reference=estimates.test[,3])




#step 1d: Seed matrix augmentation

gList <- gListFromRF(trainSet=trainSet.30sam)

augTrain <- ADAPTS::AugmentSigMatrix(origMatrix = seedMat, fullData = trainSet.3sam, gList = gList, nGenes = 1:100, newData = trainSet.3sam, plotToPDF = FALSE, pdfDir = '.')
estimates.augment <- as.data.frame(ADAPTS::estCellPercent.DCQ(augTrain, pseudobulk.test))
colnames(estimates.augment) <- paste('aug')
estimates.test <- cbind(estimates.augment, estimates.test)
resList[['testAcc.aug']] <-augAcc<-calcAcc(estimates=estimates.test[,1], reference=estimates.test[,4])




#step 1e: Shrink the augmented matrix to minimize the condition number

#sigGlist<-shrinkByKappa (augTrain, numChunks=NULL, verbose=TRUE, plotIt=TRUE, singleCore=FALSE, fastStop=FALSE)
if(skipShrink == FALSE) {
augTrain.shrink <- shrinkSigMatrix(augTrain, numChunks=NULL, verbose=TRUE, plotIt=TRUE, sigGenesList=NULL, singleCore=FALSE, fastStop=TRUE) #fastStop==TRUE overwriting aggressiveMin option.
estimates.shrink <- as.data.frame(ADAPTS::estCellPercent.DCQ(augTrain.shrink, pseudobulk.test))
colnames(estimates.shrink)<-'shrink'
dim(augTrain.shrink)
pheatmap(augTrain.shrink)
estimates.test <- cbind(estimates.shrink, estimates.test)
resList[['testAcc.shrink']] <-augshrunkAcc<-calcAcc(estimates=estimates.test[,1], reference=estimates.test[,5])
}


#step 2 clustering
varClusts <- ADAPTS::clustWspillOver(sigMatrix = seedMat, geneExpr = trainSet.3sam)
metaCluster.id <- list()
  for(i in 1:length(varClusts$allClusters)) {
    for (x in varClusts$allClusters[[i]]) {
      metaCluster.id[[x]] <- paste('Meta',i,sep='_')
    }
  }

metaClust.LUT <-  unlist(metaCluster.id)  

metatrainSet<-trainSet
metatestSet<-testSet

colnames(metatrainSet) <- metaClust.LUT[sub('\\..*','',colnames(metatestSet))]
colnames(metatestSet) <- metaClust.LUT[sub('\\..*','', colnames(metatestSet))]

metatrainSet.3sam <- ADAPTS::scSample(RNAcounts = metatrainSet, groupSize = 3, randomize = TRUE)
metatrainSet.30sam <- ADAPTS::scSample(RNAcounts = metatrainSet, groupSize = 30, randomize = TRUE)
metaclusterIDs <- factor(colnames(metatrainSet.30sam))
metatrainSet.4reg <- t(metatrainSet.30sam)
metapseudobulk.train <- data.frame(train=rowSums(metatrainSet))
metapseudobulk.train.counts <- table(sub('\\..*','', colnames(metatrainSet)))
metapseudobulk.test <- data.frame(test=rowSums(metatestSet))
metapseudobulk.test.counts <- table(sub('\\..*','', colnames(metatestSet)))
metaactFrac.test <- 100 * metapseudobulk.test.counts / sum(metapseudobulk.test.counts)

genesInSeed <- 100
metaseedMat <- buildSeed(trainSet=metatrainSet, trainSet.3sam = metatrainSet.3sam, trainSet.30sam = metatrainSet.30sam, genesInSeed = genesInSeed, groupSize = 30, randomize = TRUE, num.trees = 1000, plotIt = TRUE)

estimates.Meta.onTest <- as.data.frame(ADAPTS::estCellPercent.DCQ(metaseedMat, metapseudobulk.test))
colnames(estimates.Meta.onTest)<-'metaseed'
estimates.Meta.onTest$metaactFrac.test <- round(metaactFrac.test[rownames(estimates.Meta.onTest)],2)
resList[['testAcc.metaseed']]<-metaseedAcc<-calcAcc(estimates=estimates.Meta.onTest[,1], reference=estimates.Meta.onTest[,2])


metaallGeneSig <- apply(metatrainSet.3sam, 1, function(x){tapply(x, colnames(metatrainSet.3sam), mean, na.rm=TRUE)})
metaestimates.allGene <- as.data.frame(ADAPTS::estCellPercent.DCQ(t(metaallGeneSig), metapseudobulk.test))
colnames(metaestimates.allGene)<-'meta.all'
estimates.Meta.onTest <- cbind(metaestimates.allGene, estimates.Meta.onTest)
resList[['testAcc.metaAll']]<-metaallAcc<-calcAcc(estimates=estimates.Meta.onTest[,1], reference=estimates.Meta.onTest[,3])

metagList <- gListFromRF(trainSet=metatrainSet.30sam)

metaaugTrain <- ADAPTS::AugmentSigMatrix(origMatrix = metaseedMat, fullData = metatrainSet.3sam, gList = metagList, nGenes = 1:100, newData = metatrainSet.3sam, plotToPDF = FALSE, pdfDir = '.')
estimates.Meta.augment <- as.data.frame(ADAPTS::estCellPercent.DCQ(metaaugTrain, metapseudobulk.test))
colnames(estimates.Meta.augment) <- paste('Augmented Meta')
estimates.Meta.onTest <- cbind(estimates.Meta.augment, estimates.Meta.onTest)
resList[['testAcc.metaAug']] <- metaaugAcc<-calcAcc(estimates=estimates.Meta.onTest[,1], reference=estimates.Meta.onTest[,4])

if(skipShrink == FALSE) {
metaaugTrain.shrink <- shrinkSigMatrix(sigMatrix=metaaugTrain, numChunks=50, verbose=TRUE, plotIt = TRUE, aggressiveMin=TRUE, fastStop=TRUE, singleCore=TRUE)
estimates.Meta.shrink <- as.data.frame(ADAPTS::estCellPercent.DCQ(metaaugTrain.shrink, metapseudobulk.test))
colnames(estimates.Meta.shrink) <- paste('Shrunk Meta')
estimates.Meta.onTest <- cbind(estimates.Meta.shrink, estimates.Meta.onTest)
resList[['testAcc.metaAugShrink']] <-metashrunkAcc <-calcAcc(estimates=estimates.Meta.onTest[,1], reference=estimates.Meta.onTest[,5])
}


#decontable<-cbind(seedAcc,allAcc,augAcc,augshrunkAcc,metaseedAcc,metaallAcc,metaaugAcc,metashrunkAcc)

#print(decontable)
return(resList)

}
```

loop
```{r}
allResListOut <- list()
outFile <- paste('normal', 10,Sys.Date(), 'RData', sep='.')
for (i in 1:10) {
  curName <- paste0('res', i)
  allResListOut[[curName]] <- try(scMatrixTest(normalData, randomize = TRUE))
  save(allResListOut, file=outFile, compress='xz', version=2)
}

findConvergenceIter <- function(curSeq, changePer=1, winSize=5) {
  
  #Note, this will remove NAs.  Is that best?  They're caused by bad correlations
  runMean <- sapply(1:length(curSeq), function(x) {sum(curSeq[1:x], na.rm=TRUE)/x})
      #Criteria: running mean has changed less than 5% in the last 5? point
  convIter <- as.numeric(NA)
  if (length(runMean) > winSize) {
    winOffset <- winSize-1
    maxWinChange <- sapply(winSize:length(runMean), function(x) {
      win <- runMean[(x-winOffset):x]
      max(abs((win - mean(win))/mean(win)))
    }) #maxWinChange
    mwcBool <- maxWinChange < changePer/100
    if(any(mwcBool)) {convIter <- winOffset + which(mwcBool)[1]}
  }
  return (convIter)
}

metaAnalysis <- function (allResList) {
  testNames <- unique(sub('^.*\\.', '', names(allResList[[1]])))
  testNames <- testNames[!testNames %in% c("onTest", "allClusters", "LUT")]
  compTypes <- names(allResList[[1]][[paste0('testAcc.', testNames[1])]])
  
  allResList <- allResList[!sapply(allResList, function(x){inherits(x,'try-error')})]
  
  compList <- list()
  for (curName in testNames) {
    compList[[curName]] <- list()
    for (curComp in compTypes) {
      compList[[curName]][[curComp]] <- sapply(allResList, function(x){ 
        y <- x[[paste0('testAcc.', curName)]]
        if(!inherits(y, 'try-error')) {return(y[[curComp]])} else {return(as.numeric(NA))}  
        #If only two clusters, set correlation to zero or NA?
      }) #compList[[curName]][[curComp]] <- sapply(allResList, function(x){ 
    } #for (curComp in compTypes) {
  } #for (curName in testNames) {
  
  curColN <- unlist(lapply(compTypes, function(x){c(x, paste0(x,'.sd'))}))
  resMat <- matrix(as.numeric(NA), nrow=length(testNames), ncol=length(curColN),
                   dimnames=list(testNames, curColN))
  convMat <- matrix(as.numeric(NA), nrow=length(testNames), ncol=length(compTypes),
                   dimnames=list(testNames, compTypes))
  for (curName in testNames) {
    for (curComp in compTypes) {
      curMean <- mean(compList[[curName]][[curComp]], na.rm = TRUE)
      curSD <- sd(compList[[curName]][[curComp]], na.rm = TRUE)
      resMat[curName,curComp] <- curMean
      resMat[curName,paste0(curComp,'.sd')] <- curSD
      
      #Also test for convergence by % of change with each additional
      convMat[curName, curComp] <- findConvergenceIter(curSeq=compList[[curName]][[curComp]], changePer=1, winSize=5)
      
    } #for (curComp in compTypes) {
  } #for (curName in testNames) {
  colnames(convMat) <- paste0('convIt.',colnames(convMat))
  
  resMat <- as.data.frame(resMat)
  resMat$N <- length(allResList)
  resMat <- cbind(resMat, as.data.frame(convMat))
  
  return(resMat)
}
allResListOut <- get(load(outFile)[1])
meta <- metaAnalysis(allResListOut)
round(meta, 2)

```

